/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import view.TelaProcurar;

public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/view/nota.ico")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBackground = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFicheiro = new javax.swing.JMenu();
        miSair = new javax.swing.JMenuItem();
        menuContatos = new javax.swing.JMenu();
        miNovo = new javax.swing.JMenuItem();
        menuProcurar = new javax.swing.JMenu();
        miProcurar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AGENDA");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/nota.ico")).getImage()
        );
        setName("telaAgenda"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/background-img.png"))); // NOI18N
        lblBackground.setMinimumSize(new java.awt.Dimension(400, 234));

        menuFicheiro.setText("Ficheiro");

        miSair.setText("Sair");
        menuFicheiro.add(miSair);

        jMenuBar1.add(menuFicheiro);

        menuContatos.setText("Contatos");

        miNovo.setText("Novo");
        miNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNovoActionPerformed(evt);
            }
        });
        menuContatos.add(miNovo);

        jMenuBar1.add(menuContatos);

        menuProcurar.setText("Procurar");

        miProcurar.setText("Procurar");
        miProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProcurarActionPerformed(evt);
            }
        });
        menuProcurar.add(miProcurar);

        jMenuBar1.add(menuProcurar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNovoActionPerformed
        new TelaNovoContato().setVisible(true);
    }//GEN-LAST:event_miNovoActionPerformed

    private void miProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProcurarActionPerformed
        new TelaProcurar().setVisible(true);
    }//GEN-LAST:event_miProcurarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JMenu menuContatos;
    private javax.swing.JMenu menuFicheiro;
    private javax.swing.JMenu menuProcurar;
    private javax.swing.JMenuItem miNovo;
    private javax.swing.JMenuItem miProcurar;
    private javax.swing.JMenuItem miSair;
    // End of variables declaration//GEN-END:variables
}
